"""Per-message identity and completion bookkeeping (WP7).

No OAI ground truth. Message/frame/PDU-set identity is a pure simulator-side
scoring construct -- no real network element ever learns "message 4172
exists," only aggregate per-LCG bytes (``sim/bsr.py``, ``sim/ul_access.py``
are untouched by this module and stay that way). This module exists purely
so the scorecard can answer "did THIS message arrive by its deadline"
instead of approximating it from head-of-line age. See CLAUDE.md's standing
question -- "which network element would actually learn this" -- the answer
here is deliberately "none."

One ``Message`` maps to exactly one buffer chunk (``sim/buffer.py``). A
video frame's PDU set is modelled as several sibling ``Message``s sharing
one ``frame_id``, each its own chunk -- not one message spanning several
chunks. That keeps the drain/expire bookkeeping in ``BufferModel`` simple
(a chunk is fully delivered or fully dropped, never "half a message") while
still letting frame-level completeness be computed by grouping completions
by ``frame_id`` after the fact (``FrameLedger`` below).
"""

from dataclasses import dataclass, field
from itertools import count


@dataclass
class Message:
    """One discrete unit of traffic, generated by ``sim/traffic.py`` and
    enqueued as exactly one ``BufferModel`` chunk.

    ``delivered_bytes`` is mutated by ``BufferModel`` as the chunk drains
    across possibly-several ``drain()`` calls -- it is the only mutable
    field, and only ``BufferModel`` writes it. Everything else is fixed at
    generation time.
    """

    id: int
    ue_id: int
    qfi: int
    size_bytes: int
    generation_ts_s: float
    # Groups sibling PDUs of one video frame / lidar sweep into a PDU set.
    # None for flows with no PDU-set structure (most traffic).
    frame_id: int | None = None
    # Tags a sub-stream within a multi-rate flow (WP7 MAVLink cadence,
    # e.g. "heartbeat" vs "telemetry") so a consumer (M03's liveness gap)
    # can select just that role's messages out of a shared port/flow.
    role: str = "data"
    delivered_bytes: int = field(default=0, compare=False)


@dataclass(frozen=True)
class MessageCompletion:
    """Recorded once per message, the moment its chunk is fully resolved
    (either fully drained or fully dropped on PDB expiry -- never both)."""

    message: Message
    complete: bool  # True: every byte delivered. False: some bytes dropped.
    late: bool  # True if delivery finished after the message's own PDB.
    completion_ts_s: float
    delivered_bytes: int
    dropped_bytes: int


class MessageLedger:
    """Issues message ids and stores every ``MessageCompletion`` recorded
    by ``BufferModel``. One ledger per ``driver.run()`` call, threaded
    through exactly like ``Metrics``.
    """

    def __init__(self) -> None:
        self._id_counter = count(1)
        self._completions: list[MessageCompletion] = []

    def new_id(self) -> int:
        return next(self._id_counter)

    def record(self, completion: MessageCompletion) -> None:
        self._completions.append(completion)

    def completions(self) -> list[MessageCompletion]:
        return list(self._completions)

    def completions_for(self, ue_id: int, qfi: int) -> list[MessageCompletion]:
        return [
            c for c in self._completions
            if c.message.ue_id == ue_id and c.message.qfi == qfi
        ]
