"""Per-message identity and completion bookkeeping (WP7).

No OAI ground truth. Message/frame/PDU-set identity is a pure simulator-side
scoring construct -- no real network element ever learns "message 4172
exists," only aggregate per-LCG bytes (``sim/bsr.py``, ``sim/ul_access.py``
are untouched by this module and stay that way). This module exists purely
so the scorecard can answer "did THIS message arrive by its deadline"
instead of approximating it from head-of-line age. See CLAUDE.md's standing
question -- "which network element would actually learn this" -- the answer
here is deliberately "none."

One ``Message`` maps to exactly one buffer chunk (``sim/buffer.py``). A
video frame's PDU set is modelled as several sibling ``Message``s sharing
one ``frame_id``, each its own chunk -- not one message spanning several
chunks. That keeps the drain/expire bookkeeping in ``BufferModel`` simple
(a chunk is fully delivered or fully dropped, never "half a message") while
still letting frame-level completeness be computed by grouping completions
by ``frame_id`` after the fact (``FrameLedger`` below).
"""

from dataclasses import dataclass, field
from itertools import count


@dataclass
class Message:
    """One discrete unit of traffic, generated by ``sim/traffic.py`` and
    enqueued as exactly one ``BufferModel`` chunk.

    ``delivered_bytes`` is mutated by ``BufferModel`` as the chunk drains
    across possibly-several ``drain()`` calls -- it is the only mutable
    field, and only ``BufferModel`` writes it. Everything else is fixed at
    generation time.
    """

    id: int
    ue_id: int
    qfi: int
    size_bytes: int
    generation_ts_s: float
    # Groups sibling PDUs of one PDU set into a frame -- currently only
    # sim/traffic.py's xr_video generator assigns this (video frames); a
    # lidar sweep or similar would fit the same mechanism but isn't built.
    # None for flows with no PDU-set structure (most traffic).
    frame_id: int | None = None
    # Tags a sub-stream within a multi-rate flow (WP7 MAVLink cadence,
    # e.g. "heartbeat" vs "telemetry") so a consumer (M03's liveness gap)
    # can select just that role's messages out of a shared port/flow.
    role: str = "data"
    delivered_bytes: int = field(default=0, compare=False)


@dataclass(frozen=True)
class MessageCompletion:
    """Recorded once per message, the moment its chunk is fully resolved
    (either fully drained or fully dropped on PDB expiry -- never both)."""

    message: Message
    complete: bool  # True: every byte delivered. False: some bytes dropped.
    late: bool  # True if delivery finished after the message's own PDB.
    completion_ts_s: float
    delivered_bytes: int
    dropped_bytes: int


class MessageLedger:
    """Issues message ids and stores every ``MessageCompletion`` recorded
    by ``BufferModel``. One ledger per ``driver.run()`` call, threaded
    through exactly like ``Metrics``.
    """

    def __init__(self) -> None:
        self._id_counter = count(1)
        self._completions: list[MessageCompletion] = []
        self._drain_calls = 0
        self._drained_count = 0

    def new_id(self) -> int:
        return next(self._id_counter)

    def record(self, completion: MessageCompletion) -> None:
        self._completions.append(completion)

    @property
    def drained(self) -> bool:
        return self._drain_calls > 0

    @property
    def drained_count(self) -> int:
        """Completions handed to a window sink and forgotten."""
        return self._drained_count

    def _refuse_if_drained(self, what: str) -> None:
        if self._drain_calls:
            raise RuntimeError(
                f"{what} on a ledger that was drained {self._drain_calls} "
                f"time(s) by windowed eviction: this would return only the "
                f"tail since the last drain, which is indistinguishable from "
                f"a small real run. {self._drained_count} completions were "
                f"already handed to the window sink -- score per window."
            )

    def completions(self) -> list[MessageCompletion]:
        self._refuse_if_drained("completions()")
        return list(self._completions)

    def drain(self) -> list[MessageCompletion]:   # noqa: D401
        """Return everything recorded since the last drain, and forget it.

        WP9 G11 commit 2. A 30-minute soak generates completions without
        bound -- measured at ~24 GiB of per-message bookkeeping at 7.2M
        slots, HALF of it surviving ``record_timeseries=False``, with no
        flag to disable it (``docs/wp9-plan.md`` §37). G11 scores in 60 s
        windows and never needs the whole run at once, so a windowed
        consumer takes each window's completions and lets them go.

        DRAINING BREAKS RUN-LEVEL AGGREGATES AND THAT IS NOT HIDDEN.
        ``sim/driver.py``'s end-of-run per-flow block computes latency
        percentiles, ``completion_ts_by_role_s`` and ``frame_completions``
        from ``completions_for()``; after a drain those would be computed
        over the last partial window only. Percentiles are not associative,
        so they cannot be reassembled from per-window summaries either.
        The driver therefore emits them as ``None`` when a window sink is
        active, rather than a number that looks right -- see its
        ``window_sink`` parameter.
        """
        out = self._completions
        self._completions = []
        self._drain_calls += 1
        self._drained_count += len(out)
        return out

    def completions_for(self, ue_id: int, qfi: int) -> list[MessageCompletion]:
        self._refuse_if_drained("completions_for()")
        return [
            c for c in self._completions
            if c.message.ue_id == ue_id and c.message.qfi == qfi
        ]


def message_latency_percentiles_ms(completions: list[MessageCompletion]) -> dict:
    """True per-message completion-latency percentiles (ms), over only the
    *fully delivered* messages in ``completions``. A dropped message has no
    delivery latency to contribute -- it's scored by M02
    (config/metric_panel.yml), not blended into this percentile.

    Same percentile-index convention as ``sim.metrics.Metrics._percentile``
    (``k = min(len-1, int(len*p))``), so a diff between this and the old
    head-of-line proxy is attributable to the sample set, not a formula
    change.
    """
    delays_ms = sorted(
        (c.completion_ts_s - c.message.generation_ts_s) * 1000.0
        for c in completions if c.complete
    )
    if not delays_ms:
        return {"p50": 0.0, "p95": 0.0, "p98": 0.0, "p99": 0.0, "count": 0}

    def pct(p: float) -> float:
        k = min(len(delays_ms) - 1, int(len(delays_ms) * p))
        return delays_ms[k]

    return {
        "p50": pct(0.50), "p95": pct(0.95), "p98": pct(0.98), "p99": pct(0.99),
        "count": len(delays_ms),
    }


@dataclass(frozen=True)
class FrameCompletion:
    """One frame's (PDU set's) resolved outcome, derived from its sibling
    fragment ``MessageCompletion``s sharing one ``frame_id`` -- WP7 commit 6,
    what this module's docstring above forward-referenced from commit 1.
    ``complete`` is True iff every fragment was fully delivered (one frame
    = one PDU set, so any dropped/partial fragment fails the whole frame,
    per config/metric_panel.yml M05's own definition)."""

    frame_id: int
    generation_ts_s: float
    complete: bool
    # Latest fragment's completion timestamp -- only meaningful, and only
    # set, when complete. An incomplete frame has no single "arrival" instant.
    completion_ts_s: float | None
    fragment_count: int
    delivered_fragment_count: int


class FrameLedger:
    """Groups ``MessageCompletion``s sharing one ``frame_id`` into one
    ``FrameCompletion`` per frame -- computed post-hoc from completions
    already collected by ``MessageLedger``, not a separate id-issuing
    ledger like it (``frame_id`` already exists on ``Message``, assigned at
    generation time by ``sim/traffic.py``'s ``xr_video`` generator).

    Call with one flow's completions (e.g.
    ``MessageLedger.completions_for(ue_id, qfi)``), not the whole ledger's:
    ``frame_id`` is only unique within one flow, since each flow's
    ``xr_video`` generator counts its own frames from 0 independently.
    """

    @staticmethod
    def group(completions: list[MessageCompletion]) -> list[FrameCompletion]:
        by_frame: dict[int, list[MessageCompletion]] = {}
        for c in completions:
            if c.message.frame_id is not None:
                by_frame.setdefault(c.message.frame_id, []).append(c)
        out: list[FrameCompletion] = []
        for frame_id, frags in by_frame.items():
            complete = all(f.complete for f in frags)
            out.append(FrameCompletion(
                frame_id=frame_id,
                generation_ts_s=frags[0].message.generation_ts_s,
                complete=complete,
                completion_ts_s=max(f.completion_ts_s for f in frags) if complete else None,
                fragment_count=len(frags),
                delivered_fragment_count=sum(1 for f in frags if f.complete),
            ))
        return out
